#!C:\Users\fazlu\Working_space\VS_Code_env\Concreate_compressive_strength_project\myenv\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
